### PR TITLE
Function/Test Creation

### PR DESCRIPTION
**Pull request by manninosi**
Created function "bit_chop" to select specific bits from a decimal value. Created "pipeout_assemble" to convert a bytearray that is read from the FPGA Opal Kelly board to a decimal array. Copied "detect_peaks" function to find indices of peaks in a gamma spectrum. Tests are available for each of the functions.

### CODE REVIEW

**Review by sczyz — COMMENTED** [review]
**Regarding .pytest_cache/v/cache:** are these files essential for your code? Or should these caches be omitted via .gitignore?

**Regarding bit_chop:** you might want to make a condition that msb must be greater than lsb. Also, as a point of curiosity, what does it actually mean to get a negative remaining_bits value, in terms of what the code does from there?

**Regarding ok.analysis:** this seems to be an extraordinarily useful bit of code... I might utilize it in my own project if I am able to do a comparison between ROI method and Maximum Likelihood method

**Comment by manninosi** [comment]
The cache files are not necessary. I did not add my .gitignore until after I ran my initial tests. I'll delete those and then see if they are still catching. 

Good catch on the bit_chop function. I added a simple check that warns the user that the msb is less than the lsb. 

I also thought that peak detector was really nice, should make life easy for creating a histogram calibration curve.

**Review by sczyz — APPROVED** [review]

**Comment by sczyz** [comment]
Comments by file:

**osu_rad_settings**

- Why are all these _xem.______ _ files commented out? Are they relics of a previous version of a code that you are now converting into python, or are they commented out simply to get travis to run without error, or...? As a note, am I interpreting this file correctly in the sense that you set  whatever parameters you want in it, and then it will create a settings file automatically for it all to load in via _xem._ at once? Is that why the _xem._______ _ are all commented out? Or am I grossly misinterpreting what's going on?

**Ok_Analysis**

- Should you be defining _ __author__ _ and _ __version__ _ and the like inside of the function detect_peaks()? Otherwise it is unclear which function the handles are referring to without looking at the function file itself.

**Ok_funcs**

- same question as above regarding all instances of _xem._____ _ 

**test_OK**

- I'd suggest making more robust doc strings inside each function such that calling help(_function_) will output said doc string. This would make the code a bit longer, but it might not be a bad idea as then the doc strings can be known without looking at the actual test_OK file.
- Describe each input variable for each function in the doc string if they have input variables
- I'd suggest removing the last line of this in your final product (the test should already be run by travis right)?

**Comment by sczyz** [comment]
Overall these are minor changes. Additionally, all your files pass travis without issue, so I will merge

**Comment by manninosi** [comment]
Thanks, Steve! I'll address each comment. 

**osu_rad_settings**
This file is currently being used to create the "settings.csv" file that will be read in by the RadDevice() class. All of the xem.___ were commented out since those are the commands read by the Opal Kelly (ok package) to update the wireins, so I didn't want them to run in this code. Overall, I may just remove the file from the package, but it might serve as a simple example file. 

**Ok_Analysis** 

I just did a little searching and found that these "dunders" (i.e. author, version, etc) are supposed to go after the overall module doc-string. These attributes are not typically associated with a function, thus I simple just added those lines to the doc string of the detect peaks function. 

**Ok_Funcs** 

The xem refers to the XEM160KT FPGA we are using in our lab. The following line of code,
       ` self.xem = ok.okCFrontPanel()`
effectively establishes the connection between the PC and the FPGA. I commented those out since I don't have the API package installed at my home computer and was testing out the basic functionality of other parts of the RadDevice() class. 

**Test_OK**

I agree, I'll go and add some more explanation, so people can see what exactly it is that I'm testing.

**Pull request merged**
